### ISSUE TITLE
Skills issue

### ISSUE THREAD

**Issue by RamezAnton** [SDClowen/RSBot#429]
While training mode on bow skills 
bot attack 2 skills or 1 skill then auto attack and continue to attack more 1 or 2 skills then auto attack again
om not sure this problem on all skills or only bow but with wizard skills working fine

**Comment by yumperz** [comment]
Can confirm with nuker. Only the first skill is fired (Flame wave - arrow).
After every attack the following exception is thrown. 

I guess because of the exception the cooldown is not set so it is considered as "CanBeCasted".

`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt16()
   at RSBot.Core.Network.Packet.ReadUShort() in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Network\Packet.cs:line 398
   at RSBot.Core.Objects.Position.FromPacketInt(Packet packet) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Objects\Position.cs:line 243
   at RSBot.Core.Objects.Action.SerializeDetail(Packet packet) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Objects\Action.cs:line 173
   at RSBot.Core.Objects.Action.DeserializeBegin(Packet packet) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Objects\Action.cs:line 98
   at RSBot.Core.Network.Handler.Agent.Action.ActionSkillCastResponse.Invoke(Packet packet) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Network\Handler\Agent\Action\ActionSkillCastResponse.cs:line 65
   at RSBot.Core.Network.PacketManager.CallHandler(Packet packet, PacketDestination destination) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Network\PacketManager.cs:line 85
   at RSBot.Core.Network.Proxy.HandleReceivedPacket(Packet packet, PacketDestination destination) in E:\Projects\git\rsbot_fork\Library\RSBot.Core\Network\Socket\Proxy.cs:line 191`

**Comment by SDClowen** [comment]
On which client you are getting these errors?

**Comment by yumperz** [comment]
ISro

**Comment by RamezAnton** [comment]
> On which client you are getting these errors?

vsro

**Comment by SDClowen** [comment]
fixed forget to close
