### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Eq30** [SDClowen/RSBot#661]
**Version :**
 - SRO version: [SRO-R PServer Sailo CAP]
 - RSBot version : [e.g. v2.3]

**Describe the bug**
Client not Start - Unhandled exaptation

**Screenshots**
 screenshots to help explain the problem.
![1](https://github.com/SDClowen/RSBot/assets/130864244/143e8abf-e088-47d3-8fab-58ae2930bb1d)

**Comment by Eq30** [comment]
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at RSBot.Core.Game.Start() in C:\Users\SDClowen\source\repos\RSBot\Library\RSBot.Core\Game.cs:line 131
   at RSBot.General.Views.Main.StartClientProcess() in C:\Users\SDClowen\source\repos\RSBot\Plugins\RSBot.General\Views\Main.cs:line 188
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)


************** Loaded Assemblies ************** etc

**Comment by SDClowen** [comment]
RSBot doesn't support the salior online!
